Update e2e.yml
Given that compile work, add in the test run

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -34,3 +34,25 @@ jobs:
           run: |
             npm install
           working-directory: ./automation-tests
+        - name: Install the SFDX CLI
+          run: npm install -g sfdx-cli
+        - name: Verify CLI
+          shell: bash
+          run: |
+            set -e
+            sfdx version
+            SFDX_CLI_VERSION=$(sfdx version)
+            if [[ ((`echo $SFDX_CLI_VERSION | grep -c "sfdx-cli/"` > 0))]]
+            then
+              echo "sfdx-cli installed -" $SFDX_CLI_VERSION
+            else
+              echo "The sfdx-cli installation could not be verified"
+              exit 1
+            fi
+        - name: Run headless test
+          uses: GabrielBB/xvfb-action@v1
+          with:
+            run: npm run automation-tests
+            working-directory: ./automation-tests
+          env:
+            VSCODE_VERSION: ${{ matrix.vscodeVersion }}
